name: example
description: Widget and function to implement hashtag-decorated EditableText and RichText. Decorate the words which start with `#`
version: 1.0.0
homepage: https://pub.dev/packages/hashtagable_v3
repository: https://github.com/emmanuel-montoya/hashtagable_v3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hashtagable:

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  hashtagable_v3:
    path: ../

# The following section is specific to Flutter.
flutter:
