name: hashtagable_v3
description: Widgets and functions to implement hashtag decorated text. Decorates the words which start with `#` like a Twitter.
version: 3.0.1
homepage: https://pub.dev/packages/hashtagable_v3
repository: https://github.com/emmanuel-montoya/hashtagable_v3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

